export const CHANNEL_ID = 'C041FSKE8NQ';
export const NOTIFICATION_THREE_DAYS = 3;
export const NOTIFICATION_TWO_DAYS = 2;
export const NOTIFICATION_ONE_DAY = 1;
export const FIRST_MESSAGE_DAY = 20;
export const FINAL_MESSAGE_DAY = 25;
export const FIRST_NOTIFICATION_DAY =
  FINAL_MESSAGE_DAY - NOTIFICATION_THREE_DAYS;
export const SECOND_NOTIFICATION_DAY =
  FINAL_MESSAGE_DAY - NOTIFICATION_TWO_DAYS;
export const THIRD_NOTIFICATION_DAY = FINAL_MESSAGE_DAY - NOTIFICATION_ONE_DAY;
